# Generated by Django 5.0.6 on 2024-06-11 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0003_alter_team_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='model_notes',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
