# Generated by Django 5.0.6 on 2024-07-11 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0005_organization_manager_organization_model_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='model_notes',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='team',
            name='model_notes',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Notes'),
        ),
    ]
