# Generated by Django 5.0.6 on 2024-05-17 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itam', '0002_alter_softwareversion_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicesoftware',
            name='version',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='itam.softwareversion'),
        ),
    ]
