# Generated by Django 5.0.8 on 2024-10-10 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itam', '0004_alter_deviceoperatingsystem_device_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicesoftware',
            name='action',
            field=models.CharField(blank=True, choices=[('1', 'Install'), ('0', 'Remove')], default=None, help_text='Action to perform', max_length=1, null=True, verbose_name='Action'),
        ),
        migrations.AlterField(
            model_name='devicesoftware',
            name='installed',
            field=models.DateTimeField(blank=True, help_text='Date detected as installed', null=True, verbose_name='Date Installed'),
        ),
        migrations.AlterField(
            model_name='devicesoftware',
            name='installedversion',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='installedversion', to='itam.softwareversion', verbose_name='Installed Version'),
        ),
        migrations.AlterField(
            model_name='devicesoftware',
            name='version',
            field=models.ForeignKey(blank=True, default=None, help_text='Version to install', null=True, on_delete=django.db.models.deletion.CASCADE, to='itam.softwareversion', verbose_name='Desired Version'),
        ),
    ]
