# Generated by Django 5.0.6 on 2024-05-18 15:20

import access.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0001_initial'),
        ('itam', '0004_operatingsystem_operatingsystemversion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operatingsystemversion',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Major Version'),
        ),
        migrations.CreateModel(
            name='DeviceOperatingSystem',
            fields=[
                ('is_global', models.BooleanField(default=False)),
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('created', access.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False)),
                ('modified', access.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False)),
                ('version', models.CharField(max_length=15, verbose_name='Installed Version')),
                ('device', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='itam.device')),
                ('operating_system_version', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='itam.operatingsystemversion', verbose_name='Operating System/Version')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='access.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
