# Generated by Django 5.0.6 on 2024-05-20 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itam', '0005_alter_operatingsystemversion_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devicesoftware',
            options={'ordering': ['-action', 'software']},
        ),
        migrations.AddField(
            model_name='deviceoperatingsystem',
            name='installdate',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Install Date'),
        ),
        migrations.AddField(
            model_name='devicesoftware',
            name='installed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Install Date'),
        ),
        migrations.AddField(
            model_name='devicesoftware',
            name='installedversion',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='installedversion', to='itam.softwareversion'),
        ),
        migrations.AlterField(
            model_name='devicesoftware',
            name='action',
            field=models.CharField(blank=True, choices=[('1', 'Install'), ('0', 'Remove')], default=None, max_length=1, null=True),
        ),
    ]
