# Generated by Django 5.1.2 on 2024-10-13 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itam', '0007_alter_devicemodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deviceoperatingsystem',
            options={'ordering': ['device'], 'verbose_name': 'Device Operating System', 'verbose_name_plural': 'Device Operating Systems'},
        ),
    ]
