# Generated by Django 5.1.2 on 2024-10-13 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itam', '0008_alter_deviceoperatingsystem_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devicesoftware',
            options={'ordering': ['-action', 'software'], 'verbose_name': 'Device Software', 'verbose_name_plural': 'Device Softwares'},
        ),
    ]
