# Generated by Django 5.1.2 on 2024-10-13 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itam', '0009_alter_devicesoftware_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devicetype',
            options={'ordering': ['name'], 'verbose_name': 'Device Type', 'verbose_name_plural': 'Device Types'},
        ),
    ]
