# Generated by Django 5.0.6 on 2024-05-23 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_manufacturer'),
        ('itam', '0009_devicemodel_device_device_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatingsystem',
            name='publisher',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.manufacturer'),
        ),
    ]
