# Generated by Django 5.1.2 on 2024-10-13 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itam', '0010_alter_devicetype_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operatingsystem',
            options={'ordering': ['name'], 'verbose_name': 'Operating System', 'verbose_name_plural': 'Operating Systems'},
        ),
    ]
