# Generated by Django 5.0.6 on 2024-05-23 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_manufacturer'),
        ('itam', '0010_operatingsystem_publisher_software_publisher'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='publisher',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.manufacturer'),
        ),
    ]
