# Generated by Django 5.1.2 on 2024-10-13 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itam', '0011_alter_operatingsystem_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operatingsystemversion',
            options={'ordering': ['name'], 'verbose_name': 'Operating System Version', 'verbose_name_plural': 'Operating System Versions'},
        ),
    ]
