# Generated by Django 5.0.6 on 2024-05-28 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itam', '0011_software_publisher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='serial_number',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, unique=True, verbose_name='Serial Number'),
        ),
    ]
