# Generated by Django 5.1.2 on 2024-10-13 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itam', '0012_alter_operatingsystemversion_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='software',
            options={'ordering': ['name', 'publisher__name'], 'verbose_name': 'Software', 'verbose_name_plural': 'Softwares'},
        ),
    ]
