# Generated by Django 5.1.2 on 2024-10-13 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itam', '0013_alter_software_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='softwarecategory',
            options={'ordering': ['name'], 'verbose_name': 'Software Category', 'verbose_name_plural': 'Software Categories'},
        ),
    ]
