# Generated by Django 5.1.2 on 2024-10-20 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itam', '0016_alter_devicesoftware_action'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='softwareversion',
            options={'ordering': ['name'], 'verbose_name': 'Software Version', 'verbose_name_plural': 'Software Versions'},
        ),
    ]
