# Generated by Django 5.1.2 on 2024-10-13 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config_management', '0003_alter_configgroups_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configgroups',
            options={'ordering': ['name'], 'verbose_name': 'Config Group', 'verbose_name_plural': 'Config Groups'},
        ),
    ]
