# Generated by Django 5.0.6 on 2024-06-11 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_management', '0004_configgroupsoftware'),
    ]

    operations = [
        migrations.AddField(
            model_name='configgrouphosts',
            name='model_notes',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='configgroups',
            name='model_notes',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='configgroupsoftware',
            name='model_notes',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
