# Generated by Django 5.0.6 on 2024-07-11 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_management', '0005_configgrouphosts_model_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configgrouphosts',
            name='model_notes',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='configgroups',
            name='model_notes',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='configgroupsoftware',
            name='model_notes',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Notes'),
        ),
    ]
