# Generated by Django 5.1.2 on 2024-10-16 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_management', '0006_alter_configgrouphosts_group_and_more'),
        ('itam', '0015_alter_device_device_model_alter_device_device_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configgroups',
            name='hosts',
            field=models.ManyToManyField(blank=True, help_text='Hosts that are part of this group', to='itam.device', verbose_name='Hosts'),
        ),
    ]
