# Generated by Django 5.1.2 on 2024-10-16 06:54

from django.db import migrations, models


def migrate_to_configgroups_hosts(apps, schema_editor):

    if schema_editor.connection.alias != "default":

        return

    print('')

    ConfigGroups = apps.get_model('config_management', 'ConfigGroups')
    ConfigGroupHosts = apps.get_model('config_management', 'ConfigGroupHosts')

    current_data = ConfigGroupHosts.objects.all()

    for host in current_data:

        print(f'Begin migrating host {host.host} in group {host.group}:')

        config_group = ConfigGroups.objects.get(pk = host.group.id)

        print(f'    migrate {host.host} in group {config_group}')

        config_group.hosts.add( host.host )

        try:

            was_migrated = ConfigGroups.objects.get(pk = host.group.id)

            if host.host in was_migrated.hosts.all():

                print(f'    successfully migrated {host.id} {host.host} to new table')

                ConfigGroupHosts.objects.get(pk = host.id).delete()

                try:

                    ConfigGroupHosts.objects.get(pk = host.id)

                    print(f'    Error Failed to remove old data for host {host.host}')

                except ConfigGroupHosts.DoesNotExist:

                    print(f'    Old data removed')

        except ConfigGroupHosts.DoesNotExist:

            print(f'    Error, {host.host} was not migrated to new table')


    old_data = ConfigGroupHosts.objects.all()

    if len(old_data) == 0:

        print(f'Successfully migrated data to new table, removing old table')

        migrations.DeleteModel("ConfigGroupHosts")






class Migration(migrations.Migration):

    dependencies = [
        ('config_management', '0007_configgroups_hosts'),
    ]

    operations = [
       migrations.RunPython(migrate_to_configgroups_hosts),
    ]
