# Generated by Django 5.1.2 on 2024-10-17 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_management', '0008_move_data_configgroup_hosts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configgroupsoftware',
            name='action',
            field=models.IntegerField(blank=True, choices=[(1, 'Install'), (0, 'Remove')], default=None, help_text='ACtion to perform with this software', null=True, verbose_name='Action'),
        ),
    ]
