# Generated by Django 5.0.8 on 2024-09-16 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='external_ref',
            field=models.IntegerField(blank=True, default=None, help_text='External System reference', null=True, verbose_name='Reference Number'),
        ),
        migrations.AddField(
            model_name='project',
            name='external_system',
            field=models.IntegerField(blank=True, choices=[], default=None, help_text='External system this item derives', null=True, verbose_name='External System'),
        ),
    ]
