# Generated by Django 5.0.8 on 2024-09-17 03:14

import access.fields
import access.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0001_initial'),
        ('assistance', '0001_initial'),
        ('project_management', '0002_project_external_ref_project_external_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='external_system',
            field=models.IntegerField(blank=True, choices=[(1, 'Github'), (2, 'Gitlab'), (9999, 'Custom #1 (Imported)'), (9998, 'Custom #2 (Imported)'), (9997, 'Custom #3 (Imported)'), (9996, 'Custom #4 (Imported)'), (9995, 'Custom #5 (Imported)'), (9994, 'Custom #6 (Imported)'), (9993, 'Custom #7 (Imported)'), (9992, 'Custom #8 (Imported)'), (9991, 'Custom #9 (Imported)')], default=None, help_text='External system this item derives', null=True, verbose_name='External System'),
        ),
        migrations.CreateModel(
            name='ProjectState',
            fields=[
                ('is_global', models.BooleanField(default=False)),
                ('model_notes', models.TextField(blank=True, default=None, null=True, verbose_name='Notes')),
                ('id', models.AutoField(help_text='State ID Number', primary_key=True, serialize=False, unique=True, verbose_name='Number')),
                ('created', access.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False)),
                ('modified', access.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False)),
                ('name', models.CharField(help_text='Name of thee project state.', max_length=50, unique=True, verbose_name='Name')),
                ('is_completed', models.BooleanField(default=False, help_text='Is this state considered complete', verbose_name='State Completed')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='access.organization', validators=[access.models.TenancyObject.validatate_organization_exists])),
                ('runbook', models.ForeignKey(blank=True, help_text='The runbook for this project state', null=True, on_delete=django.db.models.deletion.SET_NULL, to='assistance.knowledgebase', verbose_name='Runbook')),
            ],
            options={
                'verbose_name': 'Project State',
                'verbose_name_plural': 'Project States',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='state',
            field=models.ForeignKey(help_text='Staate of the project', null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_management.projectstate', verbose_name='ProjectState'),
        ),
    ]
