# Generated by Django 5.0.8 on 2024-09-18 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0009_alter_project_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Is this project_considered deleted', verbose_name='Deleted'),
        ),
    ]
