# Generated by Django 5.0.8 on 2024-09-18 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0010_project_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Is this project considered deleted', verbose_name='Deleted'),
        ),
    ]
