# Generated by Django 5.0.8 on 2024-09-18 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0011_alter_project_is_deleted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['code', 'name'], 'permissions': [('import_project', 'Can import a project')], 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
    ]
