# Generated by Django 5.0.8 on 2024-09-18 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0012_alter_project_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmilestone',
            name='description',
            field=models.TextField(blank=True, default=None, help_text='Description of milestone. Markdown supported', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='projectmilestone',
            name='project',
            field=models.ForeignKey(help_text='Project this milestone belongs.', on_delete=django.db.models.deletion.CASCADE, to='project_management.project'),
        ),
    ]
