# Generated by Django 5.0.8 on 2024-10-05 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0013_alter_projectmilestone_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='projectmilestone',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
