# Generated by Django 5.1.2 on 2024-10-21 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itim', '0005_alter_cluster_cluster_type_alter_cluster_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='port',
            options={'ordering': ['number', 'protocol'], 'verbose_name': 'Port', 'verbose_name_plural': 'Ports'},
        ),
        migrations.AlterField(
            model_name='port',
            name='protocol',
            field=models.CharField(choices=[('TCP', 'TCP'), ('UDP', 'UDP')], help_text='Layer 4 Network Protocol', max_length=3, verbose_name='Protocol'),
        ),
    ]
