# Generated by Django 5.1.2 on 2024-10-13 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_externallink_cluster'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='externallink',
            options={'ordering': ['name', 'organization'], 'verbose_name': 'External Link', 'verbose_name_plural': 'External Links'},
        ),
    ]
