# Generated by Django 5.0.6 on 2024-05-24 23:19

import access.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

from django.contrib.auth.models import User

def add_app_settings(apps, schema_editor):

    app = apps.get_model('settings', 'appsettings')

    if not app.objects.filter(owner_organization=None).exists():

        setting = app.objects.create(
            owner_organization=None
        )

        setting.save()



class Migration(migrations.Migration):

    dependencies = [
        ('access', '0002_alter_team_organization'),
        ('settings', '0004_appsettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(add_app_settings),
    ]
