# Generated by Django 5.0.6 on 2024-05-27 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0002_alter_team_organization'),
        ('settings', '0005_create_settings_for_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='software_categories_is_global',
            field=models.BooleanField(default=False, verbose_name='All Software Categories are global'),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='global_organization',
            field=models.ForeignKey(blank=True, default=None, help_text='Organization global items will be created in', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='global_organization', to='access.organization'),
        ),
    ]
