# Generated by Django 5.1.2 on 2024-10-13 15:27

import access.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0003_alter_organization_id_alter_organization_manager_and_more'),
        ('settings', '0005_alter_externallink_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsettings',
            name='device_model_is_global',
            field=models.BooleanField(default=False, help_text='Should Device Models be global', verbose_name='Global Device Models'),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='device_type_is_global',
            field=models.BooleanField(default=False, help_text='Should Device Types be global', verbose_name='Global Device Types'),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='global_organization',
            field=models.ForeignKey(blank=True, default=None, help_text='Organization global items will be created in', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='global_organization', to='access.organization', verbose_name='Global Organization'),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='id',
            field=models.AutoField(help_text='Id of this setting', primary_key=True, serialize=False, unique=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='manufacturer_is_global',
            field=models.BooleanField(default=False, help_text='Should Manufacturers / Publishers be global', verbose_name='Global Manufacturers / Publishers'),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='owner_organization',
            field=models.ForeignKey(blank=True, default=None, help_text='Organization the settings belong to', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='owner_organization', to='access.organization'),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='software_categories_is_global',
            field=models.BooleanField(default=False, help_text='Should Software be global', verbose_name='Global Software Categories'),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='software_is_global',
            field=models.BooleanField(default=False, help_text='Should Software be global', verbose_name='Global Software'),
        ),
        migrations.AlterField(
            model_name='externallink',
            name='id',
            field=models.AutoField(help_text='ID for this external link', primary_key=True, serialize=False, unique=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='externallink',
            name='is_global',
            field=models.BooleanField(default=False, help_text='Is this a global object?', verbose_name='Global Object'),
        ),
        migrations.AlterField(
            model_name='externallink',
            name='model_notes',
            field=models.TextField(blank=True, default=None, help_text='Tid bits of information', null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='externallink',
            name='organization',
            field=models.ForeignKey(help_text='Organization this belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, to='access.organization', validators=[access.models.TenancyObject.validatate_organization_exists], verbose_name='Organization'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='default_organization',
            field=models.ForeignKey(blank=True, default=None, help_text='Users default Organization', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='access.organization', verbose_name='Default Organization'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='id',
            field=models.AutoField(help_text='ID for this user Setting', primary_key=True, serialize=False, unique=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='user',
            field=models.ForeignKey(help_text='User this Setting belongs to', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
