# Generated by Django 5.0.6 on 2024-05-27 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_appsettings_software_categories_is_global_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='device_model_is_global',
            field=models.BooleanField(default=False, verbose_name='All Device Models are global'),
        ),
    ]
