# Generated by Django 5.0.6 on 2024-05-27 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_appsettings_device_model_is_global'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='device_type_is_global',
            field=models.BooleanField(default=False, verbose_name='All Device Types is global'),
        ),
    ]
