# Generated by Django 5.0.6 on 2024-05-27 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0008_appsettings_device_type_is_global'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='manufacturer_is_global',
            field=models.BooleanField(default=False, verbose_name='All Manufacturer / Publishers are global'),
        ),
    ]
