# Generated by Django 5.0.6 on 2024-07-11 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0009_appsettings_manufacturer_is_global'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Settings',
        ),
    ]
