# Generated by Django 5.0.6 on 2024-05-20 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('itam', '0007_device_inventorydate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='serial_number',
        ),
        migrations.AlterField(
            model_name='notes',
            name='device',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='itam.device'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='operatingsystem',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='itam.operatingsystem'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='software',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='itam.software'),
        ),
    ]
