# Generated by Django 5.0.6 on 2024-05-23 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0002_alter_team_organization'),
        ('core', '0003_alter_notes_note_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='access.organization'),
        ),
    ]
