# Generated by Django 5.1.2 on 2024-10-11 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_ticket_milestone_ticket_opened_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='after',
            field=models.JSONField(blank=True, default=None, help_text='JSON Object After Change', null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='before',
            field=models.JSONField(blank=True, default=None, help_text='JSON Object before Change', null=True),
        ),
    ]
