# Generated by Django 5.0.8 on 2024-09-16 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_ticket_milestone_ticket_opened_by_and_more'),
        ('project_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='milestone',
            field=models.ForeignKey(blank=True, help_text='Assign to a milestone', null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_management.projectmilestone', verbose_name='Project Milestone'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Assign to a project', null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_management.project', verbose_name='Project'),
        ),
    ]
