# Generated by Django 5.0.6 on 2024-06-02 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_management', '0001_initial'),
        ('core', '0006_alter_history_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='config_group',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='config_management.configgroups'),
        ),
    ]
