# Generated by Django 5.0.8 on 2024-09-16 05:19

import core.models.ticket
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_ticket_milestone_alter_ticket_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='external_system',
            field=models.IntegerField(blank=True, choices=[], default=None, help_text='External system this item derives', null=True, verbose_name='External System'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='impact',
            field=models.IntegerField(blank=True, choices=[], default=('1', 'Very Low'), help_text='End user assessed impact', null=True, verbose_name='Impact'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.IntegerField(blank=True, choices=[], default=('1', 'Very Low'), help_text='What priority should this ticket for its completion', null=True, verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.IntegerField(choices=[], default=('2', 'New'), help_text='Status of ticket', verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_type',
            field=models.IntegerField(choices=[], help_text='The type of ticket this is', validators=[core.models.ticket.Ticket.validation_ticket_type], verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='urgency',
            field=models.IntegerField(blank=True, choices=[], default=('1', 'Very Low'), help_text='How urgent is this tickets resolution for the user?', null=True, verbose_name='Urgency'),
        ),
        migrations.AlterField(
            model_name='ticketcomment',
            name='external_system',
            field=models.IntegerField(blank=True, choices=[], default=None, help_text='External system this item derives', null=True, verbose_name='External System'),
        ),
    ]
