# Generated by Django 5.0.6 on 2024-06-11 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_manufacturer_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='model_notes',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='notes',
            name='model_notes',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
