# Generated by Django 5.1.2 on 2024-10-13 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_manufacturer_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notes',
            options={'ordering': ['-created'], 'verbose_name': 'Note', 'verbose_name_plural': 'Notes'},
        ),
    ]
