# Generated by Django 5.0.8 on 2024-09-18 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_ticket_external_system_alter_ticket_impact_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketcategory',
            options={'ordering': ['parent__name', 'name'], 'verbose_name': 'Ticket Category', 'verbose_name_plural': 'Ticket Categories'},
        ),
    ]
