# Generated by Django 5.0.8 on 2024-09-20 05:50

import access.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0001_initial'),
        ('core', '0010_alter_ticketcategory_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketLinkedItem',
            fields=[
                ('id', models.AutoField(help_text='ID Number', primary_key=True, serialize=False, unique=True, verbose_name='Number')),
                ('item_type', models.IntegerField(choices=[(1, 'Cluster'), (2, 'Config Group'), (3, 'Device'), (4, 'Operating System'), (5, 'Service'), (6, 'Software')], help_text='Python Model location for linked item', verbose_name='Item Type')),
                ('item', models.IntegerField(help_text='Item ID to link to ticket', verbose_name='Item ID')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='access.organization', validators=[access.models.TenancyObject.validatate_organization_exists])),
                ('ticket', models.ForeignKey(help_text='Ticket the item will be linked to', on_delete=django.db.models.deletion.CASCADE, to='core.ticket', verbose_name='Ticket')),
            ],
            options={
                'verbose_name': 'Ticket Linked Item',
                'verbose_name_plural': 'Ticket linked Items',
                'ordering': ['id'],
            },
        ),
    ]
