# Generated by Django 5.1.2 on 2024-10-18 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_history_action_alter_history_after_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'ordering': ['-created'], 'verbose_name': 'History', 'verbose_name_plural': 'History'},
        ),
        migrations.AlterField(
            model_name='history',
            name='action',
            field=models.IntegerField(choices=[(1, 'Create'), (2, 'Update'), (3, 'Delete')], default=None, help_text='History action performed', null=True, verbose_name='Action'),
        ),
    ]
