# Generated by Django 5.0.8 on 2024-09-21 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_ticketlinkeditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='estimate',
            field=models.IntegerField(default=0, help_text='Time Eastimated to complete this ticket in seconds', verbose_name='Estimation'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.TextField(help_text='Ticket Description', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='ticketcomment',
            name='body',
            field=models.TextField(help_text='Comment contents', verbose_name='Comment'),
        ),
    ]
