# Generated by Django 5.1.2 on 2024-10-19 03:58

import access.fields
import django.utils.timezone
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_notes_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='modified',
            field=access.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, help_text='Date and time of last modification', verbose_name='Modified'),
        ),
    ]
