# Generated by Django 5.0.8 on 2024-10-10 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_ticket_estimate_alter_ticket_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='after',
            field=models.JSONField(blank=True, default=None, help_text='JSON Object After Change', null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='before',
            field=models.JSONField(blank=True, default=None, help_text='JSON Object before Change', null=True),
        ),
    ]
