# Generated by Django 5.1.2 on 2024-10-26 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_manufacturer_modified'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketcomment',
            options={'ordering': ['created', 'ticket', 'parent_id'], 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
    ]
