# Generated by Django 5.1.2 on 2024-11-03 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_ticketcomment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relatedtickets',
            options={'ordering': ['id'], 'verbose_name': 'Related Ticket', 'verbose_name_plural': 'Related Tickets'},
        ),
        migrations.AlterModelOptions(
            name='ticketcomment',
            options={'ordering': ['created', 'ticket', 'parent_id'], 'verbose_name': 'Ticket Comment', 'verbose_name_plural': 'Ticket Comments'},
        ),
    ]
